[connections.snowflake]
account = "SFSEAPAC-KSHIMADA_SEAPACORG_AWSAPNE1_CRITICAL_STD"
user = "kshimada"
authenticator = "externalbrowser"
warehouse = "DEMOAPP"
database = "DEMOAPP"
schema = "DOCUMENT_EXTRACTION"
